name: tv_guardian
description: Cocuk mesafe koruma - Android TV WiFi kontrolu

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Kamera + yuz tespiti
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0

  # Sesli uyari (Turkce TTS)
  flutter_tts: ^4.0.2

  # Sesli komut
  speech_to_text: ^6.6.2

  # Ayarlari kaydet
  shared_preferences: ^2.2.3

  # Izin isteme
  permission_handler: ^11.3.1

  # State management
  flutter_riverpod: ^2.5.1

  # mDNS - agdaki TV leri bul
  multicast_dns: ^0.3.2+1
  network_info_plus: ^5.0.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
